### PR TITLE
Removed deprecated functions

### PR DESCRIPTION
**Pull request by memnoth**
- gdk_keymap_get_default is deprecated in Gtk 3.22, it could be replaced with gdk_keymap_get_for_display.
- gdk_beep is deprecated in Gtk 3.22, it could be replaced with gdk_display_beep.

### CODE REVIEW

**Comment by cogniti** [comment]
Thank you for your patch.
But `gdk_keymap_get_default()` and `gdk_beep()` are not deprecated in GDK 3.22.

**Comment by memnoth** [comment]
In Gtk 3.22.26, `gdk_keymap_get_default` and `gdk_keymap_get_for_display` made compilation error that used deprecated functions.
Also gdk_keymap_get_default and gdk_keymap_get_for_display have been dropped since Dec 15, 2017.
https://gitlab.gnome.org/GNOME/gtk/commits/master/gdk/gdkkeys.h?utf8=%E2%9C%93&search=gdk_keymap

**Comment by cogniti** [comment]
`gdk_keymap_get_default()` and `gdk_beep()` are not deprecated in GDK 3.22.26.

**Comment by cogniti** [comment]
The current version of https://packages.ubuntu.com/bionic/libgtk-3-dev is 3.22.26-2ubuntu1.
Successfully built on ubuntu bionic.
https://launchpad.net/~hodong/+archive/ubuntu/testing/+build/14332890 (This link will be removed in the future)

**Comment by cogniti** [comment]
`gdk_keymap_get_default()` and `gdk_beep()` are not deprecated in GDK 3.22.7

**Comment by cogniti** [comment]
Please use versioned GTK.
`gdk_keymap_get_default()` and `gdk_beep()` are deprecated in GDK 3.22.27

```
commit 299a91bd46a1970f33ffcd2f3fad2894b3f762dd
Author: Emmanuele Bassi <ebassi@gnome.org>
Date:   Sun Feb 11 15:07:24 2018 +0000

    docs: Properly deprecate gdk_keymap_get_default()

    We're using a compiler annotation, but there's no deprecation
    notice in
    the gtk-doc stanza.

 gdk/gdkkeys.c | 2 ++
 1 file changed, 2 insertions(+)

commit 9c6ae95eceaa018b872cbf3937e66fd06804067b
Author: Emmanuele Bassi <ebassi@gnome.org>
Date:   Sun Feb 11 15:06:04 2018 +0000

    accelgroup: Do not use deprecated API

    Use gdk_keymap_get_for_display() with the default display, instead of
    the deprecated gdk_keymap_get_default().

 gtk/gtkaccelgroup.c | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)
```
```
hodong@debian:~/Downloads/gtk+-3.22.27/gtk+-3.22.27/gdk$ grep GDK_DEPRECATED_IN_3_22_FOR -R
gdkmain.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_x11_display_error_trap_push)
gdkmain.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_x11_display_error_trap_pop)
gdkmain.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_x11_display_error_trap_pop_ignored)
gdkmain.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_display_set_double_click_time)
gdkmain.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_display_beep)
gdkmain.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_display_flush)
gdkcairo.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_window_begin_draw_frame() and gdk_drawing_context_get_cairo_context())
gdkwindow.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_window_begin_draw_frame)
gdkwindow.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_window_begin_draw_frame)
gdkwindow.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_window_end_draw_frame)
gdkversionmacros.h:# define GDK_DEPRECATED_IN_3_22_FOR(f)        GDK_DEPRECATED_FOR(f)
gdkversionmacros.h:# define GDK_DEPRECATED_IN_3_22_FOR(f)        _GDK_EXTERN
gdkversionmacros.h.in:# define GDK_DEPRECATED_IN_3_22_FOR(f)        GDK_DEPRECATED_FOR(f)
gdkversionmacros.h.in:# define GDK_DEPRECATED_IN_3_22_FOR(f)        _GDK_EXTERN
gdkvisual.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_screen_get_system_visual)
gdkvisual.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_screen_list_visuals)
gdkkeys.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_keymap_get_for_display)
gdkscreen.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_display_get_n_monitors)
gdkscreen.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_display_get_primary_monitor)
gdkscreen.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_monitor_get_geometry)
gdkscreen.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_monitor_get_workarea)
gdkscreen.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_display_get_monitor_at_point)
gdkscreen.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_display_get_monitor_at_window)
gdkscreen.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_monitor_get_width_mm)
gdkscreen.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_monitor_get_height_mm)
gdkscreen.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_monitor_get_model)
gdkscreen.h:GDK_DEPRECATED_IN_3_22_FOR(gdk_monitor_get_scale_factor)
```

**Pull request merged**
